### ISSUE TITLE
bugfix(): ImagePush function | capture name of the built image name, tag and push the resultant image according 

### ISSUE THREAD

**Issue by AniketKul** [ocibuilder/ocibuilder#70]
**Describe the bug**
At present, users need to provide the image name as a combination of `registry`, `user` and `image-name` in `ocibuilder.yaml`. Ideally users should provide just the `image-name` and `ImagePush()` function from `pkg/docker.go` should take care of tagging the image appropriately and pushing it to the registry/registries mentioned in push specs of `ocibuilder.yaml` file

**Current Spec**

```
build:
  templates:
    - name: template-1
      cmd:
        - docker:
            inline:
              - RUN mkdir /dirname
              - WORKDIR /dirname
              - COPY * /dirname/
              - EXPOSE 8888
  steps:
    - metadata:
        name: <registry>/<namespace>/<image-name>
        labels:
          type: build-1
          overlay: overlay-1
      stages:
        - metadata:
            name: build-env
            labels:
              stage: stage-1
              type: build-from-base
          base:
            image: python
            platform: alpine
          template: template-1
      tag: v0.0.1
      distroless: false
      cache: false
      purge: false
```

**Expected Spec**

```
build:
  templates:
    - name: template-1
      cmd:
        - docker:
            inline:
              - RUN mkdir /dirname
              - WORKDIR /dirname
              - COPY * /dirname/
              - EXPOSE 8888
  steps:
    - metadata:
        name: **<image-name>**
        labels:
          type: build-1
          overlay: overlay-1
      stages:
        - metadata:
            name: build-env
            labels:
              stage: stage-1
              type: build-from-base
          base:
            image: python
            platform: alpine
          template: template-1
      tag: v0.0.1
      distroless: false
      cache: false
      purge: false
```
